version: '3'
services:
  restAPI:
    image: maven:3.8-openjdk-17
    volumes:
      - './src:/tmp/src'
      - './pom.xml:/tmp/pom.xml'
      - './output/:/tmp/output/'
    working_dir: '/tmp'
    command: 'mvn spring-boot:run'
    ports:
      - "8080:8080"
  testAPI:
    image: maven:3.8-openjdk-17
    volumes:
      - './src:/tmp/src'
      - './pom.xml:/tmp/pom.xml'
      - './output/:/tmp/output/'
    working_dir: '/tmp'
    command: 'mvn test'